import { readFileSync } from "node:fs";

export const RECYCLING_REGIONS = ["macau", "taipa", "coloane"];

// Scan categories the classifier can return, and the recycling stream each one
// needs. Categories with no stream (general waste, unknown, organic) cannot be
// matched to a drop-off point.
export const SCAN_CATEGORIES = ["plastic", "paper", "metal", "glass", "electronic", "organic", "general_waste", "unknown"];
const CATEGORY_STREAMS = { plastic: "plastic", paper: "paper", metal: "metal", glass: "glass", electronic: "electronic" };

const DEFAULT_LIMIT = 100;
const MAX_LIMIT = 500;

/**
 * Load the captured DSPA recycling point list and wrap it in a small query API.
 * The data file is generated by `scripts/import-recycling-points.mjs`; this
 * module never contacts the DSPA website at request time.
 */
export function loadRecyclingPoints(fileUrl = new URL("../data/macau-recycling-points.json", import.meta.url)) {
  const dataset = JSON.parse(readFileSync(fileUrl, "utf8"));
  return createRecyclingPointsApi(dataset);
}

export function createRecyclingPointsApi(dataset) {
  if (!dataset || !Array.isArray(dataset.channels) || !Array.isArray(dataset.sources)) {
    throw new Error("Recycling points data is malformed.");
  }
  const channelById = new Map(dataset.channels.map((channel) => [channel.id, channel]));
  const sourceById = new Map(dataset.sources.map((source) => [source.id, source]));

  // Flatten every point that has official coordinates once, so the nearest-point
  // search does not need to walk each channel on every request.
  const locatedPoints = dataset.channels.flatMap((channel) =>
    channel.locations
      .filter((location) => Number.isFinite(location.latitude) && Number.isFinite(location.longitude))
      .map((location) => ({ channelId: channel.id, channelName: channel.name, accepts: channel.accepts, ...location }))
  );

  function regionCounts(locations) {
    const counts = Object.fromEntries(RECYCLING_REGIONS.map((region) => [region, 0]));
    for (const location of locations) {
      if (counts[location.region] !== undefined) counts[location.region] += 1;
    }
    return counts;
  }

  function summarize(channel) {
    return {
      id: channel.id,
      name: channel.name,
      nameZh: channel.nameZh,
      accepts: channel.accepts,
      note: channel.note,
      officialFinder: channel.officialFinder,
      sourceIds: channel.sourceIds,
      count: channel.locations.length,
      located: channel.locations.filter((location) => Number.isFinite(location.latitude) && Number.isFinite(location.longitude)).length,
      regions: regionCounts(channel.locations)
    };
  }

  return {
    accessed: dataset.accessed,
    sourceNote: dataset.sourceNote,
    coordinateNote: dataset.coordinateNote,
    locatedTotal: locatedPoints.length,
    listChannels() {
      return {
        accessed: dataset.accessed,
        sourceNote: dataset.sourceNote,
        coordinateNote: dataset.coordinateNote,
        locatedTotal: locatedPoints.length,
        total: dataset.channels.reduce((total, channel) => total + channel.locations.length, 0),
        channels: dataset.channels.map(summarize),
        sources: dataset.sources
      };
    },
    getChannel(channelId, options = {}) {
      const channel = channelById.get(channelId);
      if (!channel) return null;
      const region = options.region || "";
      const query = (options.query || "").trim().toLowerCase();
      const limit = clampInteger(options.limit, 1, MAX_LIMIT, DEFAULT_LIMIT);
      const offset = clampInteger(options.offset, 0, 1_000_000, 0);

      let locations = channel.locations;
      if (region) locations = locations.filter((location) => location.region === region);
      if (query) {
        locations = locations.filter((location) => `${location.name} ${location.address} ${location.detail || ""}`.toLowerCase().includes(query));
      }

      return {
        channel: summarize(channel),
        total: locations.length,
        limit,
        offset,
        locations: locations.slice(offset, offset + limit),
        sources: channel.sourceIds.map((id) => sourceById.get(id)).filter(Boolean)
      };
    },
    nearby(latitude, longitude, options = {}) {
      const limit = clampInteger(options.limit, 1, 20, 5);
      const category = options.category || "";
      const stream = category ? CATEGORY_STREAMS[category] || null : null;
      // With a category, keep only points whose channel accepts that stream, so a
      // suggestion is only ever a place that recycles the scanned material.
      const pool = category ? (stream ? locatedPoints.filter((location) => location.accepts.includes(stream)) : []) : locatedPoints;
      const ranked = pool
        .map((location) => ({ ...location, distanceMeters: Math.round(haversineMeters(latitude, longitude, location.latitude, location.longitude)) }))
        .sort((a, b) => a.distanceMeters - b.distanceMeters);
      return {
        origin: { latitude, longitude },
        category: category || null,
        stream,
        locatedTotal: locatedPoints.length,
        matchingTotal: pool.length,
        total: pool.length,
        coordinateNote: dataset.coordinateNote,
        locations: ranked.slice(0, limit)
      };
    }
  };
}

function haversineMeters(latA, lngA, latB, lngB) {
  const earthRadius = 6_371_000;
  const toRadians = (degrees) => (degrees * Math.PI) / 180;
  const deltaLat = toRadians(latB - latA);
  const deltaLng = toRadians(lngB - lngA);
  const a = Math.sin(deltaLat / 2) ** 2 + Math.cos(toRadians(latA)) * Math.cos(toRadians(latB)) * Math.sin(deltaLng / 2) ** 2;
  return 2 * earthRadius * Math.asin(Math.min(1, Math.sqrt(a)));
}

function clampInteger(value, min, max, fallback) {
  const parsed = typeof value === "number" ? value : Number.parseInt(value, 10);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(Math.max(Math.trunc(parsed), min), max);
}
